from html import escape
from pathlib import Path

from axiom.app import AppComponent, AppSpec, DeploySpec
from axiom.ast import Module

from .base import BuildContext, StackGenerator


class StaticSiteGenerator(StackGenerator):
    stack = "static-site"

    def build(self, context: BuildContext, modules: list[Module], apps: list[AppSpec]) -> list[Path]:
        index_path = context.build / "index.html"
        index_path.write_text(_static_site_html(context, modules, apps), encoding="utf-8")
        return [index_path]


def _static_site_html(context: BuildContext, modules: list[Module], apps: list[AppSpec]) -> str:
    sections: list[str] = []

    for app in apps:
        sections.append(_app_html(app))

    for module in modules:
        for function in module.functions:
            purpose = " ".join(function.purpose) if function.purpose else "No purpose provided."
            examples = "".join(f"<li><code>{escape(example)}</code></li>" for example in function.examples)
            if not examples:
                examples = "<li>No examples provided.</li>"
            sections.append(
                "\n".join(
                    [
                        '<section class="card">',
                        f"<h2>{escape(function.name)}</h2>",
                        f"<p>{escape(purpose)}</p>",
                        "<h3>Examples</h3>",
                        f"<ul>{examples}</ul>",
                        "</section>",
                    ]
                )
            )

    content = "\n".join(sections) or '<section class="card"><p>No Axiom functions found.</p></section>'

    return "\n".join(
        [
            "<!doctype html>",
            '<html lang="en">',
            "<head>",
            '  <meta charset="utf-8">',
            '  <meta name="viewport" content="width=device-width, initial-scale=1">',
            f"  <title>{escape(context.name)}</title>",
            "  <style>",
            "    body { font-family: system-ui, sans-serif; margin: 2rem; background: #f8fafc; color: #0f172a; }",
            "    main { max-width: 760px; margin: 0 auto; }",
            "    .card { background: white; border: 1px solid #e2e8f0; border-radius: 12px; padding: 1rem; margin: 1rem 0; }",
            "    code { background: #f1f5f9; padding: 0.1rem 0.3rem; border-radius: 4px; }",
            "  </style>",
            "</head>",
            "<body>",
            "  <main>",
            f"    <h1>{escape(context.name)}</h1>",
            "    <p>Generated by Axiom using the static-site stack.</p>",
            content,
            "  </main>",
            "</body>",
            "</html>",
            "",
        ]
    )


def _app_html(app: AppSpec) -> str:
    parts = [
        '<section class="card">',
        f"<h2>{escape(app.name)}</h2>",
        _paragraph_list("Purpose", app.purpose),
        _paragraph_list("Requirements", app.requires),
        _paragraph_list("Actions", app.action),
        _paragraph_list("Examples", app.examples),
    ]

    for component in _iter_components(app):
        parts.append(_component_html(component))

    if app.deploy is not None:
        parts.append(_deploy_html(app.deploy))

    parts.append("</section>")
    return "\n".join(parts)


def _component_html(component: AppComponent) -> str:
    stack = escape(component.stack or "not specified")
    return "\n".join(
        [
            f"<h3>{escape(component.name.title())}</h3>",
            f"<p><strong>Stack:</strong> {stack}</p>",
            _paragraph_list("Description", component.descriptions),
        ]
    )


def _deploy_html(deploy: DeploySpec) -> str:
    target = escape(deploy.target or "not specified")
    credential_note = ""
    if deploy.credentials:
        credential_note = "<p><strong>Credentials:</strong> configured outside generated code</p>"
    return "\n".join(
        [
            "<h3>Deploy</h3>",
            f"<p><strong>Target:</strong> {target}</p>",
            _paragraph_list("Description", deploy.descriptions),
            credential_note,
        ]
    )


def _paragraph_list(title: str, items: list[str]) -> str:
    if not items:
        return ""
    rendered = "".join(f"<li>{escape(item)}</li>" for item in items)
    return f"<h3>{escape(title)}</h3><ul>{rendered}</ul>"


def _iter_components(app: AppSpec) -> list[AppComponent]:
    return [component for component in [app.frontend, app.backend, app.database] if component is not None]
