import tempfile
from json import loads
from pathlib import Path

from axiom.project import (
    AxiomProjectError,
    build_project,
    create_project,
    generate_project,
    list_stacks,
    load_project,
    run_project,
)


def test_create_project_scaffolds_axiom_app():
    with tempfile.TemporaryDirectory() as tmpdir:
        root = create_project("todo-api", parent=tmpdir)

        assert root == Path(tmpdir) / "todo-api"
        assert (root / "axiom.toml").exists()
        assert (root / "src" / "main.ax").exists()
        assert 'entry = "todo_api.main"' in (root / "axiom.toml").read_text(encoding="utf-8")
        assert 'stack = "python-cli"' in (root / "axiom.toml").read_text(encoding="utf-8")
        assert "app TodoApi:" in (root / "src" / "main.ax").read_text(encoding="utf-8")


def test_build_project_generates_python_entrypoint():
    with tempfile.TemporaryDirectory() as tmpdir:
        root = create_project("todo-api", parent=tmpdir)
        outputs = build_project(root)

        output_names = {path.name for path in outputs}
        assert output_names == {"todo_api.py", "__main__.py"}
        assert "def main():" in (root / "build" / "todo_api.py").read_text(encoding="utf-8")
        assert "Axiom app: TodoApi" in (root / "build" / "todo_api.py").read_text(encoding="utf-8")


def test_run_project_executes_entrypoint():
    with tempfile.TemporaryDirectory() as tmpdir:
        root = create_project("todo-api", parent=tmpdir)
        project = load_project(root)

        assert project.entry == "todo_api.main"
        assert project.stack == "python-cli"
        assert run_project(root) == 0


def test_create_project_supports_static_site_stack():
    with tempfile.TemporaryDirectory() as tmpdir:
        root = create_project("landing-page", parent=tmpdir, stack="static-site")
        project = load_project(root)
        outputs = build_project(root)

        assert project.stack == "static-site"
        assert [path.name for path in outputs] == ["index.html"]
        assert "Generated by Axiom using the static-site stack." in outputs[0].read_text(encoding="utf-8")
        assert "LandingPage" in outputs[0].read_text(encoding="utf-8")
        assert run_project(root) == 0


def test_rejects_unknown_stack():
    with tempfile.TemporaryDirectory() as tmpdir:
        try:
            create_project("todo-api", parent=tmpdir, stack="unknown")
        except AxiomProjectError as exc:
            assert "Unsupported stack" in str(exc)
        else:
            raise AssertionError("Expected unknown stack to fail")


def test_lists_supported_stacks():
    assert list_stacks() == ["auto", "fastapi-react-sqlite", "python-cli", "static-site"]


def test_fastapi_react_sqlite_generates_login_app():
    with tempfile.TemporaryDirectory() as tmpdir:
        root = create_project("login-page", parent=tmpdir, stack="fastapi-react-sqlite")
        outputs = build_project(root)
        output_paths = {path.relative_to(root / "build").as_posix() for path in outputs}

        assert "backend/main.py" in output_paths
        assert "backend/requirements.txt" in output_paths
        assert "frontend/src/App.jsx" in output_paths
        assert "frontend/package.json" in output_paths
        assert "README.md" in output_paths

        backend = (root / "build" / "backend" / "main.py").read_text(encoding="utf-8")
        frontend = (root / "build" / "frontend" / "src" / "App.jsx").read_text(encoding="utf-8")

        assert "FastAPI" in backend
        assert "sqlite3" in backend
        assert "@app.post('/api/login')" in backend
        assert "password_hash" in backend
        assert "fetch(`${API_BASE}/api/login`" in frontend


def test_generate_project_builds_from_single_axiom_file():
    source = """
app LoginPage:
    purpose:
        Let users sign in.

    requires:
        Users can enter an email and password.

    action:
        Create a login page.

    examples:
        A valid user can sign in.

    frontend:
        stack: react
        descriptions:
            Show a login form.

    backend:
        stack: fastapi
        descriptions:
            Provide login APIs.

    database:
        stack: sqlite
        descriptions:
            Store users.
"""

    with tempfile.TemporaryDirectory() as tmpdir:
        source_path = Path(tmpdir) / "login.ax"
        output_path = Path(tmpdir) / "generated-login"
        source_path.write_text(source, encoding="utf-8")

        generated = generate_project(source_path, output=output_path, stack="fastapi-react-sqlite")

        assert generated.root == output_path
        assert (output_path / "src" / "main.ax").read_text(encoding="utf-8") == source
        assert (output_path / "build" / "backend" / "main.py").exists()
        assert (output_path / "build" / "frontend" / "src" / "App.jsx").exists()
        assert (output_path / "NEXT_STEPS.txt").exists()
        assert any("demo@example.com" in line for line in generated.next_steps)


def test_build_project_infers_stack_when_config_has_no_stack():
    source = """
app LandingPage:
    purpose:
        Explain a product.

    frontend:
        stack: static-site
        descriptions:
            Show product content.
"""

    with tempfile.TemporaryDirectory() as tmpdir:
        root = Path(tmpdir) / "landing-page"
        source_dir = root / "src"
        source_dir.mkdir(parents=True)
        (root / "axiom.toml").write_text(
            "\n".join(
                [
                    'name = "landing-page"',
                    'source = "src"',
                    'build = "build"',
                    'entry = "landing_page.main"',
                    "",
                ]
            ),
            encoding="utf-8",
        )
        (source_dir / "main.ax").write_text(source, encoding="utf-8")

        outputs = build_project(root)
        project = load_project(root)
        stack_plan = loads((root / "build" / "axiom-stack-plan.json").read_text(encoding="utf-8"))

    assert project.stack == "auto"
    assert [path.name for path in outputs] == ["index.html"]
    assert stack_plan["requested_stack"] == "auto"
    assert stack_plan["selected_stack"] == "static-site"
    assert stack_plan["inferred"] is True
    assert stack_plan["capabilities"] == ["user-interface"]


def test_generate_project_auto_stack_writes_stack_plan():
    source = """
app TodoApp:
    purpose:
        Help people track tasks.

    entities:
        Task:
            fields:
                title: Text

    pages:
        TasksPage:
            route: /tasks

    actions:
        create_task:
            effects:
                persist Task
"""

    with tempfile.TemporaryDirectory() as tmpdir:
        source_path = Path(tmpdir) / "todo.ax"
        output_path = Path(tmpdir) / "generated-todo"
        source_path.write_text(source, encoding="utf-8")

        generated = generate_project(source_path, output=output_path, stack="auto")
        stack_plan = loads((output_path / "build" / "axiom-stack-plan.json").read_text(encoding="utf-8"))
        backend_exists = (output_path / "build" / "backend" / "main.py").exists()

    assert stack_plan["requested_stack"] == "auto"
    assert stack_plan["selected_stack"] == "fastapi-react-sqlite"
    assert stack_plan["inferred"] is True
    assert backend_exists
    assert any("demo@example.com" in line for line in generated.next_steps)
