import tempfile
from pathlib import Path

from axiom.project import AxiomProjectError, build_project, create_project, list_stacks, load_project, run_project


def test_create_project_scaffolds_axiom_app():
    with tempfile.TemporaryDirectory() as tmpdir:
        root = create_project("todo-api", parent=tmpdir)

        assert root == Path(tmpdir) / "todo-api"
        assert (root / "axiom.toml").exists()
        assert (root / "src" / "main.ax").exists()
        assert 'entry = "todo_api.main"' in (root / "axiom.toml").read_text(encoding="utf-8")
        assert 'stack = "python-cli"' in (root / "axiom.toml").read_text(encoding="utf-8")
        assert "app TodoApi:" in (root / "src" / "main.ax").read_text(encoding="utf-8")


def test_build_project_generates_python_entrypoint():
    with tempfile.TemporaryDirectory() as tmpdir:
        root = create_project("todo-api", parent=tmpdir)
        outputs = build_project(root)

        output_names = {path.name for path in outputs}
        assert output_names == {"todo_api.py", "__main__.py"}
        assert "def main():" in (root / "build" / "todo_api.py").read_text(encoding="utf-8")
        assert "Axiom app: TodoApi" in (root / "build" / "todo_api.py").read_text(encoding="utf-8")


def test_run_project_executes_entrypoint():
    with tempfile.TemporaryDirectory() as tmpdir:
        root = create_project("todo-api", parent=tmpdir)
        project = load_project(root)

        assert project.entry == "todo_api.main"
        assert project.stack == "python-cli"
        assert run_project(root) == 0


def test_create_project_supports_static_site_stack():
    with tempfile.TemporaryDirectory() as tmpdir:
        root = create_project("landing-page", parent=tmpdir, stack="static-site")
        project = load_project(root)
        outputs = build_project(root)

        assert project.stack == "static-site"
        assert [path.name for path in outputs] == ["index.html"]
        assert "Generated by Axiom using the static-site stack." in outputs[0].read_text(encoding="utf-8")
        assert "LandingPage" in outputs[0].read_text(encoding="utf-8")
        assert run_project(root) == 0


def test_rejects_unknown_stack():
    with tempfile.TemporaryDirectory() as tmpdir:
        try:
            create_project("todo-api", parent=tmpdir, stack="unknown")
        except AxiomProjectError as exc:
            assert "Unsupported stack" in str(exc)
        else:
            raise AssertionError("Expected unknown stack to fail")


def test_lists_supported_stacks():
    assert list_stacks() == ["python-cli", "static-site"]
